# Generated by Django 6.0 on 2025-12-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="auctions.category",
            ),
        ),
    ]
