# Generated by Django 6.0 on 2025-12-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="actual_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
